### ISSUE TITLE
IPhone X Alert issue

### ISSUE THREAD

**Issue by sergey19941201** [AppRopio/AppRopio.Mobile#70]
Text can`t be displayed fully on iPhone X. Also if there are several lines the upper lines are hidden at all. [screenshot from ZooOptTorg](http://prntscr.com/o952ze) 
[screenshot from Incanto](http://prntscr.com/o9gl1f)

**Comment by entdark** [comment]
Fixed in 5d8e87c966f352676e12ce2d61c75fb22430b123.
